### ISSUE TITLE
node-red-contrib-scx-ibmiotapp crashing and killing node-red

### ISSUE THREAD

**Issue by knolleary** [ibm-watson-iot/iot-nodered#24] opened 2016-07-22 16:04 UTC
Getting reports of node-red crashes due to the recent update to the iotf node to use TCP rather than WebSockets.

Looks like it is missing an error handler, causing an uncaught exception to take down the app.

```
2016 3:36:21 PM	OUT	App	22 Jul 15:36:21 - Error: Connection refused: Not authorized
7/22/2016 3:36:21 PM	OUT	App	at MqttClient._handleConnack (/home/vcap/app/node_modules/node-red-contrib-scx-ibmiotapp/node_modules/ibmiotf/node_modules/mqtt/lib/client.js:673:9)
7/22/2016 3:36:21 PM	OUT	App	at MqttClient._handlePacket (/home/vcap/app/node_modules/node-red-contrib-scx-ibmiotapp/node_modules/ibmiotf/node_modules/mqtt/lib/client.js:274:12)
7/22/2016 3:36:21 PM	OUT	App	at process (/home/vcap/app/node_modules/node-red-contrib-scx-ibmiotapp/node_modules/ibmiotf/node_modules/mqtt/lib/client.js:218:12)
7/22/2016 3:36:21 PM	OUT	App	at Writable.writable._write (/home/vcap/app/node_modules/node-red-contrib-scx-ibmiotapp/node_modules/ibmiotf/node_modules/mqtt/lib/client.js:228:5)
7/22/2016 3:36:21 PM	OUT	App	at doWrite (/home/vcap/app/node_modules/node-red-contrib-scx-ibmiotapp/node_modules/ibmiotf/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:237:10)
7/22/2016 3:36:21 PM	OUT	App	at writeOrBuffer (/home/vcap/app/node_modules/node-red-contrib-scx-ibmiotapp/node_modules/ibmiotf/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:227:5)
7/22/2016 3:36:21 PM	OUT	App	at Writable.write (/home/vcap/app/node_modules/node-red-contrib-scx-ibmiotapp/node_modules/ibmiotf/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:194:11)
7/22/2016 3:36:21 PM	OUT	App	at TLSSocket.ondata (_stream_readable.js:540:20)
7/22/2016 3:36:21 PM	OUT	App	at TLSSocket.emit (events.js:107:17)
7/22/2016 3:36:21 PM	OUT	App	at readableAddChunk (_stream_readable.js:163:16)
7/22/2016 3:36:21 PM	OUT	App	at TLSSocket.Readable.push (_stream_readable.js:126:10)
7/22/2016 3:36:21 PM	OUT	App	at TCP.onread (net.js:540:20)
7/22/2016 3:36:21 PM	OUT	API	App instance exited with guid f78737eb-44df-408b-bac6-fe414d67ac5a payload: {"cc_partition"=>"default", "droplet"=>"f78737eb-44df-408b-bac6-fe414d67ac5a", "version"=>"105921b5-0514-4a66-8b83-bd940c6fe51e", "instance"=>"d7808348a79a4031a8c4c07e03c8f355", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"app instance exited", "crash_timestamp"=>1469201781}
```

**Comment by jeffdare** [comment] 2016-07-22 16:27
Hi,
The issue is not with the change to TCP, rather when a wrong credentials is passed to the **ibmapp in** node, the error (not authorized) is not handled. So we need to handle the error and pass the message to the user.

**Comment by Lokesh-K-Haralakatta** [comment] 2016-07-25 05:55
Added error handler to handle connection related errors to avoid crash. With the change, we should see the below pasted messages instead of crash:

25 Jul 11:15:10 - [info] Started flows
[BaseClient:onError] Connection Error :: Error: Connection refused: Not authorized
25 Jul 11:15:11 - [info] [ibmiot out:App Out] Error: Connection refused: Not authorized
[BaseClient:connect] Iotfclient is offline. Retrying connection
[BaseClient:onError] Connection Error :: Error: Connection refused: Not authorized
25 Jul 11:15:11 - [info] [ibmiot in:App In] Error: Connection refused: Not authorized
[BaseClient:connect] Iotfclient is offline. Retrying connection
[BaseClient:onError] Connection Error :: Error: Connection refused: Not authorized
25 Jul 11:15:15 - [info] [ibmiot in:App In] Error: Connection refused: Not authorized
[BaseClient:connect] Iotfclient is offline. Retrying connection
[BaseClient:onError] Connection Error :: Error: Connection refused: Not authorized
25 Jul 11:15:15 - [info] [ibmiot out:App Out] Error: Connection refused: Not authorized
[BaseClient:connect] Iotfclient is offline. Retrying connection
[BaseClient:onError] Connection Error :: Error: Connection refused: Not authorized
25 Jul 11:15:19 - [info] [ibmiot in:App In] Error: Connection refused: Not authorized
[BaseClient:connect] Iotfclient is offline. Retrying connection
[BaseClient:onError] Connection Error :: Error: Connection refused: Not authorized
25 Jul 11:15:19 - [info] [ibmiot out:App Out] Error: Connection refused: Not authorized
[BaseClient:connect] Iotfclient is offline. Retrying connection
^C25 Jul 11:15:22 - [info] Stopping flows

The required changes are delivered to github. Needs to be merged and released to NPM.

**Closed by Lokesh-K-Haralakatta** 2016-07-25 05:55 UTC

**Comment by Lokesh-K-Haralakatta** [comment] 2016-07-25 06:23
After changing node.log to node.error to dump error messages, the messages look as pasted below:

25 Jul 11:42:07 - [info] Started flows
[BaseClient:onError] Connection Error :: Error: Connection refused: Not authorized
25 Jul 11:42:08 - [error] [ibmiot out:App Out] Error: Connection refused: Not authorized
[BaseClient:connect] Iotfclient is offline. Retrying connection
[BaseClient:onError] Connection Error :: Error: Connection refused: Not authorized
25 Jul 11:42:08 - [error] [ibmiot in:App In] Error: Connection refused: Not authorized
[BaseClient:connect] Iotfclient is offline. Retrying connection
[BaseClient:onError] Connection Error :: Error: Connection refused: Not authorized
25 Jul 11:42:12 - [error] [ibmiot out:App Out] Error: Connection refused: Not authorized
[BaseClient:connect] Iotfclient is offline. Retrying connection
[BaseClient:onError] Connection Error :: Error: Connection refused: Not authorized
25 Jul 11:42:13 - [error] [ibmiot in:App In] Error: Connection refused: Not authorized
[BaseClient:connect] Iotfclient is offline. Retrying connection
[BaseClient:onError] Connection Error :: Error: Connection refused: Not authorized
25 Jul 11:42:16 - [error] [ibmiot out:App Out] Error: Connection refused: Not authorized
[BaseClient:connect] Iotfclient is offline. Retrying connection
