### ISSUE TITLE
Node doesn't connect when used with bound service

### ISSUE THREAD

**Issue by knolleary** [ibm-watson-iot/iot-nodered#26] opened 2016-07-26 09:05 UTC
The ibmiot nodes no longer connect when used with a bound service in Bluemix. This means the out-of-the-box example flow doesn't work.

I think the issue is the newly added keepalive setting - which doesn't exist in the credentials object provided by bluemix... but I may be wrong. This needs testing and addressing urgently.

Other issues:

**Unclosed <label> tag causes the label to look wrong**. In two places:
 - https://github.com/ibm-watson-iot/iot-nodered/blob/master/node-red-contrib-scx-ibmiotapp/application/97-iotnewapp-cf.html#L153
 - https://github.com/ibm-watson-iot/iot-nodered/blob/master/node-red-contrib-scx-ibmiotapp/application/97-iotnewapp-cf.html#L31

**Pointless logging** - we get complaints about how much this nodes logs. There are a lot of log statements that don't add any value and just add noise to the log:

 - https://github.com/ibm-watson-iot/iot-nodered/blob/master/node-red-contrib-scx-ibmiotapp/application/97-iotnewapp-cf.js#L199
 - https://github.com/ibm-watson-iot/iot-nodered/blob/master/node-red-contrib-scx-ibmiotapp/application/97-iotnewapp-cf.js#L205
 - https://github.com/ibm-watson-iot/iot-nodered/blob/master/node-red-contrib-scx-ibmiotapp/application/97-iotnewapp-cf.js#L303
 - https://github.com/ibm-watson-iot/iot-nodered/blob/master/node-red-contrib-scx-ibmiotapp/application/97-iotnewapp-cf.js#L337
 - https://github.com/ibm-watson-iot/iot-nodered/blob/master/node-red-contrib-scx-ibmiotapp/application/97-iotnewapp-cf.js#L339
 -

**Comment by sathipal** [comment] 2016-07-26 09:51
The issue is fixed now and the default flow works now. The issue is with the latest Node.js library dependency.

We are working on removing the extra logging statements and label issues.

**Comment by Lokesh-K-Haralakatta** [comment] 2016-07-27 05:32
Resoled the issue. Also removed the extra logging getting dumped with ibmiot app nodes. Changed the res.send(statusCode) to res.sendStatus(statusCode) as res.send(statusCode) getting deprecated. Tested the changes on bluemix with default flow in all 3 modes - QS, API and BlueMix, changes worked fine.

**Closed by Lokesh-K-Haralakatta** 2016-07-27 05:32 UTC
